[storyline.ardent]
id = "ardent"
dir = "Ardent"

[storyline.ardent.tags]
beta = true

[storyline.ardent.start]
location = "Tutorial_Deck"
port = "Cuba_port"
model = "Ardent"
first_name = "Charles"
last_name = "Ardent"
nation = "pirate"
player_type = "corsair"
difficulty = "seadog"
pirate_flag = 1
personal_flag = 15
ship = "Cutter1"
ship_name = "Fortune"

[storyline.new_horizons.start.editable]
difficulty = true

[storyline.ardent.start.date]
hour = 10
min = 21
sec = 32
day = 31
month = 7
year = 1691

[storyline.ardent.variables]
ISLA_DE_MUERTE = 0
START_MIN_LEVEL = 1
