"interface:credits:project_lead" = "Jefe de proyecto"
"interface:credits:scripting" = "Programación"
"interface:credits:quest_writing" = "Guión de las misiones"
"interface:credits:artwork" = "Arte"
"interface:credits:music" = "Música"
"interface:credits:engine" = "Desarrollo del motor"
"interface:credits:translation" = "Traducción"
"interface:credits:testing" = "Pruebas"
"interface:credits:build14" = "Edición 14"
