# Dialog ini file

[dialog]
namefont	= "dialog_name"
name.color = "#eecc66"
mainfont	= "DIALOG21"
subfont		= "DIALOG31"
leftIndent	= 45
rightIndent	= 40
nodes_y		= 32
nodes_n		= 0
fon_Border	= 10
fon_A		= 128
fon_R		= 11
fon_G		= 8
fon_B		= 55

[ANIMATION]
talk = "dialog_all"
yes  = "yes4"
no   = "no4"
idle = "dialog_idle"
